### ISSUE TITLE
the first lyph in a chain wired to a scaffold is not positioned correctly

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#100]
It looks like the first lyph goes perpendicular.
![wired-to-bug](https://user-images.githubusercontent.com/4299776/128235423-233a15fe-c977-4661-90bb-bbef841d1615.png)

I don't have a screenshot of it, but if there is only a single lyph in the chain it goes at a 45 degree angle.

**Comment by albatros13** [comment]
Fixed
