### ISSUE TITLE
empty namespaces should not be treated as equal

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#104]
The empty namespace needs to be assumed to be different for each model so that models don't accidentally have id collisions. When merging models use of an explicit namespace that is the same is required to get the merge to complete successfully. This avoids issues like we see when loading https://github.com/open-physiology/open-physiology-viewer/issues/77#issuecomment-900608357 into the default keast scaffold test in the viewer.
![apinat-namespace-merge-issue](https://user-images.githubusercontent.com/4299776/129798084-0aa3e820-e590-4bd5-8b4c-ac74a70b43ae.png)

**Comment by albatros13** [comment]
Added a line assigning missing namespace as "nm_" + model identifier

**Comment by tgbugs** [comment]
Ideally the shortened namespace would be the same across all models, but I realize that the issue is that `fullID` as implemented isn't actually a curie because we are missing a level of indirection (the `fullID` should actually be the expanded form based on a local conventions mapping, but we can deal with that at some other time).
