### ISSUE TITLE
layers need to always be present in the model even if they are not explicit

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#118]
It is painful to query for housing regions because sometimes a layer interposes and sometimes it does not. This means that two code paths are required to find the housing lyph. This means that even if not specified, or rather especially when no specified, a layer should be constructed so that we can always follow the same path `endsIn|fasciculatesIn -> layerIn -> apinatomy:external`. As it stands we have to branch on the presence or absense of `layerIn`.

**Comment by albatros13** [comment]
This is not possible without breaking the consistency of the model: layerIn is a reverse property for layers, if a lyph has no layers, filling layerIn with something is incorrect. We can create a derived property to help you find what you need, for example, see container: get container(){ return this.internalIn || this.layerIn && this.layerIn.internalIn; }
Alternatively, we can copy exernal from lyph to its layers, so you always can get your annotation via 
endsIn|fasciculatesIn -> external

**Comment by albatros13** [comment]
Added derived property "housingLyph" that can be used for simpler queries
