### ISSUE TITLE
Sharing of end nodes in housed chains

### ISSUE THREAD

**Issue by albatros13** [open-physiology/open-physiology-viewer#12]
When a chain is generated to stretch alone housing lyphs, its end points (root and leaf) are placed to the first and the last housing lyphs. This is achieved by setting the node's property "internalIn". The problem arises when a user tries to join several chains by sharing their end nodes - the same node is forced to be internal in two different lyphs causing model inconsistency. When this happens with border nodes, we clone the nodes, but no actions are taken for internal nodes.

**Comment by albatros13** [comment]
Copied comment from Tom posted in a wrong issue: 
The way that chains of chains should work is that the branching needs to happen inside of a housing lyph, but the details of the implementation mean that the housed lyphs must start at the border of the housing lyph. The pattern we want is closer to the dendrite/soma/axon topology, except that there isn't a soma. Having a virtual node doesn't work because we need to be able to answer queries of the form "show me all neurons with axons that branch in region x." Further cloning does not work because the semantics of a clone mean that all points are in the same physical location which would imply in this case that a wormhole has formed between the housing lyphs.

**Comment by albatros13** [comment]
Discussion of this issue was wrongly placed into issue #11

**Comment by tgbugs** [comment]
Here is a bit more detail, note that the upper internal lyph is really in the bottom layer I just didn't have space.
![apinat-chain-branching](https://user-images.githubusercontent.com/4299776/83300250-8bcaec00-a1ac-11ea-9750-3d406765751a.jpg)

**Comment by tgbugs** [comment]
The solution we came up with on the call is as follows.
A node id can be reused in as many disjoin lyphs as the author wants.
However for any node id used in this way the author must provide the housing lyph
where all of those instances join @albatros13 mentioned that something like `internalIn` might make sense. When the housing lyph for the node is supplied then all uses of the identifier will be transformed into new unique identifiers and a new node will be generated perhaps with `node-id-root` as the id or as the original node id (consider tradeoffs here), and will be located in the specified housing lyph. If a node id is used in multiple locations and the location of the common node is _not_ provided then an error is produced.

**Comment by albatros13** [comment]
The processing of group definitions has been extended with a method "replicateInternalNodes" which identifiers nodes claimed as internal by two or more lyphs. For each of such lyphs, we create a clone of the node and reconnect all links that the lyph bundles to the clone. The clone is then connected with the oroginal node by a collapsible link.
There are 2 questions:
- we need to include generated nodes to proper chain groups - it is not entirely clear how to find such a group.
- which node is the root or leaf of a chain in the join: the original node or its clone?

**Comment by albatros13** [comment]
The "replicateInternalNodes" auto-fix procedure for the issue above works as follows: 
1. Map all nodes in a group to lyphs in which they are internal in.
2. For each node N which is internal in 2 or more lyphs:
3.   For each lyph L in which N is internal in:
3.     N_i <- clone of the node N, N and N_i are connected vis their fields clones and cloneOf
4.     Replace references in the lyph's internalNodes array to point to N_i instead of N.
5.     targetOfLinks <- links that end in the node N and are bundled by the lyph L
6.     sourceOfLinks <- links that start in the node N and are bundled by the lyph L
7.     leafChains <- chains in which targetOfLinks are levels in
8.     rootChains <- chains in which sourceOfLinks are levels in
9.     For each chain in the rootChains and leafChains:
10.      Remove N from being the chain's root or leaf
11.      Add cloned node N_i to the chain's group
12.    Create a collapsible link between N and N_i, preseving the directions of the chains. 
13.  Add clones the node N to its controlNodes property to position N into the geometric center of its clones.

**Comment by albatros13** [comment]
Added test to chain.spec.js (Link joint chains (Keast Spinal)) to check that:
- collapsible links created for a join node
- join node was cloned
- last level of preceding chain is linked to the first level of the following chain
