### ISSUE TITLE
Add property to anchors in too-map.json

### ISSUE THREAD

**Issue by jrmartin** [open-physiology/open-physiology-viewer#120]
Cardinal nodes need to be distinguishable from other anchors

**Comment by jrmartin** [comment]
A proposal is having a property called : cardinalNode
![image](https://user-images.githubusercontent.com/4562825/139940072-39bd31ad-1d55-4bb8-9018-3a43849a58cc.png)

**Comment by albatros13** [comment]
Added property "cardinal" (cardinalNode seems inappropriate/misleading because anchor is not a node, in our class definitions)
