### ISSUE TITLE
embed snapshots in models

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#122]
Since we have import statements for models now, the best way to create snapshot demos is to create a model that imports all the components and then save the snapshots as part of that model.

**Comment by tgbugs** [comment]
There should still be an option to save the snapshots separately since there are many workflows where we want the snapshots separate, e.g. if we were to allow models to import snapshot files.

**Comment by albatros13** [comment]
If a snapshot model is provided in the "imports" field of a connectivity model, a snapshot gets loaded to the viewer.
