### ISSUE TITLE
set DNS record for docs.apinatomy.org -> https://open-physiology-viewer-docs.surge.sh/

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#123]

**Comment by tgbugs** [comment]
@jgrethe https://github.com/tgbugs/pyontutils/blob/master/nifstd/resolver/apinatomy-resolver.conf the nginx conf file has been updated and should be ready to go except for two changes once the docs.apinatomy.org redirect has been put in place.

A test server is up at http://apinatomy.olympiangods.org and some examples of test urls can be found at https://github.com/SciCrunch/sparc-curation/blob/master/docs/apinatomy.org#tests

**Comment by tgbugs** [comment]
@albatros13 can we prioritize this?

**Comment by jgrethe** [comment]
@tgbugs we will also need to schedule time to update the NGINX conf file

**Comment by albatros13** [comment]
Hi Tom,

sure, but I will need Bernard on call for that to configure DNS records for
apinatomy.org domain.

Here is the procedure:
https://surge.sh/help/adding-a-custom-domain

Regards,
Natallia

**Comment by jgrethe** [comment]
Perhaps we should schedule a 30 minute call next week to make all these changes

**Comment by albatros13** [comment]
Done and working
