### ISSUE TITLE
create canonical connectivity model for TOO map

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#125]
Should use human friendly identifier names, and should be the reference namespace for all materials and elements that are frequently reused across models.

**Comment by albatros13** [comment]
This must have been done by now - please close the issue if it's so.

**Comment by tgbugs** [comment]
Yeah this is the wbkg or the (wbrcm), we haven't fully integrated it yet, but this ticket is definitely done.
