### ISSUE TITLE
cloned lyphs should copy properties of original

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#126]
Needed to simplify queries and behavior so that if there is an external or inherited external identifier on the original it is possible to obtain that value without having to know that something is a clone.

Essentially, cloning should be invisible to someone trying to consume the knowledge encoded in a model, however right now they are impeded by the implementation details because cloned lyphs do not have the same behavior as regular lyphs (they require an additional dereference which massively complicates queries).

**Comment by albatros13** [comment]
Cloned resources inherit their properties from the original resource. For example, lyphs copy: 
color, scale, height, width, length, thickness, scale, description, create3d, materials, channels, bundlesChains
Layer structure is copied too, but with own instances of layers.
Please indicate which other properties have to be copied
