### ISSUE TITLE
zeros in chain housingLayers list missing in export

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#132]
When exporting models with chains that specify a 0th layer if that lyph does not actually have layers then the 0th layer is dropped from the list. This is a problem because if there is more than one lyph without a layer it is impossible to tell from which lyph the layer was dropped and therefore impossible to tell what the actual layer to lyph mapping should be.

This issue is directly related to the discussion of whether there can be lyphs without layers or only lyphs with a single layer. When we convert to a model where all lyphs must have at least one layer then this problem would likely disappear as well.

Example.

```json
{
      "id": "dc-bn-10",
      "name": "FOS neuron to bladder neck-dendrite chain_Neuron 10 (kblad)",
      "class": "Chain",
      "external": [
        "SAO:1211023249"
      ],
      "hidden": true,
      "group": "group_dc-bn-10",
      "root": "ns180",
      "leaf": "ns181",
      "lyphs": [
        "dc-bn-10_lyph_1",
        "dc-bn-10_lyph_2",
        "dc-bn-10_lyph_3"
      ],
      "lyphTemplate": "dend-bag",
      "numLevels": 3,
      "levels": [
        "dc-bn-10_lnk_1",
        "dc-bn-10_lnk_2",
        "dc-bn-10_lnk_3"
      ],
      "housingLyphs": [
        "n-blad",
        "K100",
        "K105"
      ],
      "housingLayers": [
        3,
        1
      ]
    },


```

**Comment by albatros13** [comment]
Fixed
