### ISSUE TITLE
Chain's startFromLeaf setting not working

### ISSUE THREAD

**Issue by albatros13** [open-physiology/open-physiology-viewer#134]
Bug in the wired chain's layout - start and end of a wired chain are swapped twice, first when ends are selected, then when chain is aligned, cancelling the effect of the startFromLeaf setting.

**Comment by albatros13** [comment]
The issue is fixed, will write a unit test

**Comment by tgbugs** [comment]
We need to get this and other fixes merged into the demo branch.

**Comment by albatros13** [comment]
The processing of the setting has been solved. A test on chain wiring ("Conflicts in chains t2 and t3 are detected) checks that root and leaf of the chain are bound to the target and the source of the wire.
