### ISSUE TITLE
Difficulty visualizing internal lyphs in brainstem structures when file is uploaded on open viewer

### ISSUE THREAD

**Issue by IliasApiNATOMY10** [open-physiology/open-physiology-viewer#137]
[Copy of COMMON_ApiNATOMY_template_IZ_SL.xlsx](https://github.com/open-physiology/open-physiology-viewer/files/7912707/Copy.of.COMMON_ApiNATOMY_template_IZ_SL.xlsx)

Hi all,
Snezana and I worked on this common file (attached here) for the Keast-bladder model. We succeded in correcting minor errors that made the file impossible to upload on the viewer giving us the same error we encountered last week "Error: TypeError: lyph.updateSize is not a function". 
However, when the file was uploaded to the viewer we have difficulty distinguishing internal lyphs and structures belonging to the brainstem to understand whether there are mistakes with the curation of the model or it is a matter of visualization.
Thank you,
Ilias

**Comment by albatros13** [comment]
The issue with the lyph.updateSize is not relevant for the test model anymore (and generally, safeguarded to never be raised again even for wrong models).  All new visualization features and requirements must be specified in separate issues on which we can act accordingly.
