### ISSUE TITLE
group visibility settings are broken

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#149]
Ungrouped is masking priority for things that have manual groups and groups that contain only groups do not work. Example attached
[pancr-copy-bad.xlsx](https://github.com/open-physiology/open-physiology-viewer/files/8091845/pancr-copy-bad.xlsx)
.

**Comment by albatros13** [comment]
1. Fixed - now group "Neuron 1" includes dynamic groups "Neuron1t5"-"Neuron 1t9"
2. "Greater splank" group remains unchanged - it will toggle 1 lyph on/off when "Ungrouped" is enabled and the lyph is visible. To show and hide the lyph, include its axis to the group.
