### ISSUE TITLE
demo merge test cannot load models

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#150]
At @bdebono's request I tried a blind merge of the current master branch into the demo branch and everything builds but I get runtime errors on launch and cannot get any models to load. The reason for this is that the attached connectivity model will not load on the demo branch but will on master.
[WBKG TOO Map Reference Connectivity.xlsx](https://github.com/open-physiology/open-physiology-viewer/files/8127261/WBKG.TOO.Map.Reference.Connectivity.xlsx)

https://github.com/tgbugs/open-physiology-viewer/tree/demo-merge

@albatros13 @enicolasgomez @jrmartin 

Example of the issue on demo-merge that happens at startup.
```
errorHandler.js:15 ReferenceError: getPoint is not defined
    at Chain../view/group.js.Chain.update (group.js:42:21)
    at group.js:94:46
    at Array.forEach (<anonymous>)
    at Graph../view/group.js.Group.updateViewObjects (group.js:94:23)
    at Object.layoutTick [as onFrame] (threeForceGraphKapsule.js:335:29)
    at Function.tickFrame (threeForceGraphKapsule.js:245:23)
    at Function.comp.<computed> [as tickFrame] (kapsule.module.js:176:1)
    at FromKapsule.<computed> [as tickFrame] (threeForceGraph.js:23:31)
    at WebGLSceneComponent.animate (webGLScene.js:478:24)
    at webGLScene.js:482:49
```

Example of the error I get when trying to load a scaffold.
```
Incorrectly defined region: cannot identify border points or anchors. At least 3 border points are needed to define a region
```

**Comment by jrmartin** [comment]
@enicolasgomez It's working on merge on the two branches ( our demo and your master), by cherry picking the auto layout code. It'll probably still take this week and early days of next week. 

We should have these issues sorted by next week's sprint. @tgbugs @bdebono

**Comment by enicolasgomez** [comment]
@jrmartin @tgbugs @bdebono this is how it looks on my branch `merge_remote` (this branch is basically yours plus our layout changes).

No errors or anything suspiciuos in the console log. 

<img width="976" alt="Screen Shot 2022-03-14 at 11 22 00" src="https://user-images.githubusercontent.com/5366927/158192125-b84d50b3-2ec6-4968-9c2a-e39a6bbc4d05.png">

**Comment by jrmartin** [comment]
@enicolasgomez Looking good. One thing we are missing, is the group 'Airways'. 

Using http://open-physiology-viewer.surge.sh/ to load the connectivity model, we should see the 'Airways' group rendered between 'X' and 'f1L'. 
![image (7)](https://user-images.githubusercontent.com/4562825/158268427-a72573cb-5787-4923-93f0-ffd153d4abb3.png)

**Comment by albatros13** [comment]
Closing because it looks like this has been solved long ago
