### ISSUE TITLE
Revise function fromJSONGenerated in converter.js 

### ISSUE THREAD

**Issue by albatros13** [open-physiology/open-physiology-viewer#156]
Model generation code was updated to work with namespaces.
In the method "fromJSONGenerated" there are considerable pieces of copied code that may need revision too (I did not dare to change it as I do not want to break the converter, although a few minor changes were made for compatibility with altered code in resourceModel.js)
Add unit test to make sure future evolution does not accidentally break the converter.

**Comment by tgbugs** [comment]
@ddelpiano wrote the majority of `fromJSONGenerated`. I don't have more than a cursory understanding of it.

**Comment by ddelpiano** [comment]
@albatros13 @tgbugs below an analysis of the differences spotted after working on this.
Also, integration tests were already available in wrapper/test, these needs to be updated if the analysis below it's fine according to the new changes done in the current master.

https://github.com/MetaCell/open-physiology-viewer/issues/162#issuecomment-1189169494

Thanks!

**Comment by albatros13** [comment]
The code was revised and merged with master, working fine
