### ISSUE TITLE
top level externals/ontologyTerms not expanding

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#166]
Some of the recent changes seem to have resulted in classes listed in `ontologyTerms` no longer being expanded and included in the combined model. Probably related to https://github.com/open-physiology/open-physiology-viewer/issues/156.

**Comment by jrmartin** [comment]
Relevant method https://github.com/open-physiology/open-physiology-viewer/blob/759d5d2e20a6383647516e3c8e689b1178f8628d/src/model/modelClasses.js#L182

**Comment by albatros13** [comment]
This was caused by the order of group merging - top-level group content was formed before ontology terms from nested subgroups were included to the groups. Fixed and test exists to make sure ontologyTerms are not lost.
