### ISSUE TITLE
need negative indexing for housingLayers

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#206]
`housingLayers` is a nightmare for human beings to maintain correctly, and the fact that 99% of the time the zeroth layer will change from tissue to fluid means that any additional modelling of a lyph will always break all models that use that lyph and force them to be refactored if they use `housingLayers`. Worse, I suspect that the code that tries to do the right thing will make these kinds of errors silent.

I suggest that we add negative indexing support for `housingLayers` as one way to avoid this by at least allowing users to indicate that they should always be in the outermost layer in the event that there is some modification of a lyph to add layers.

We also need a way indicate/handle ambiguous layer location that is not 0 and not a negative layer, but that will be another issue.

**Comment by albatros13** [comment]
Done
