### ISSUE TITLE
aacar endsIn fails to be generated correctly

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#208]
This bug may already have been fixed.

In aacar https://github.com/open-physiology/apinatomy-models/blob/410289fb2666330cbc5cd4448c58a06922ec6525/models/ard-arm-cardiac/source/ard-arm-cardiac.json

generation for `ac-ven-epi_9` produces lnk_1 with a correct endsIn
whereas for
`ac-vent-epi-term-6` and `ac-atrial-epi-term-6` folllowing the same pattern fails to generate lnk_1 with endsIn

**Comment by tgbugs** [comment]
`ac-vent-epi-term-6` and `ac-atrial-epi-term-6` should `endsIn` `A83`

**Comment by tgbugs** [comment]
Confirming that this is still present on master.

**Comment by albatros13** [comment]
There is no problem with endsIn, this is an error in the model - there is no lyph "74", there is lyph "A74". The validator warns you about it: 
Failed to find chain level housing lyph
"74"
Failed to find chain level housing lyph
"74"
After replacing 74 to A74, both links have endsIn property filled

**Comment by albatros13** [comment]
Create the related issue on apinatomy-models project https://github.com/open-physiology/apinatomy-models/issues/24
(Cannot fix myself as I do not know where the original Excel spreadsheet is, committing a copy leaves the risk that it will be overridden)
