### ISSUE TITLE
internalLyphs expansion is inconsistent

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#209]
While tracking down why bolew populations 13-29 seemed to have an extra lyph at the end, I discovered that `internalLyphs` expands differently depending on whether there is an explicit `internalLyphsInLayers`. For consistency an absent `internalLyphsInLayers` should expand to layer 0 for all lyphs.

**Comment by tgbugs** [comment]
see https://github.com/open-physiology/apinatomy-models/commit/7b232c9a8a700eb393984ea55407a932adadd834#diff-145f643a4d5c4af314b93954d8fcd5e887a8c52adfbf6f69902767aa065c7895 a workaround/what should happen behind the scenes

**Comment by albatros13** [comment]
Done! 
Exceptional case (should not occur in a correct model, but can occur in general): if the internalLyphsInLayers points to an index that is larger than the number of layers in the hosting lyph, the internalLyph remains hosted by the original hosting lyph (and warning is issued).
