### ISSUE TITLE
nextChain property to link between chains

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#21]
With the new behavior for dealing with branches implemented in issue #12 we need to make sure that we can traverse multiple chains. I suggest that we add a relationship `nextChain` between the leaf node of one chain and the root of the next chain so that the [query](https://github.com/SciCrunch/sparc-curation/blob/1580dab5ed024431d15f9008fb0ac52ace20c99e/resources/scigraph/cypher-resources.yaml#L466) can be kept as simple as possible, requiring the addition of only a single new edge type (i.e., `apinatomy:nextChain`).

**Comment by tgbugs** [comment]
https://ontology.olympiangods.org/trees/sparc/dynamic/demos/apinat/soma-processes

This is what comes out of the current query. The axon appears to terminate in `L1` rather than `IMG`. This is because `local:ac-snl18_lnk_5` is the final level in `local:ac-snl18 a elements:Chain`. This was loaded/converted using the production version, the result is the same from the latest version.
```
├──Soma of SPR neuron in L1_8
│  └──lnk-snl18
│     └──ns25
│        ├──L1-8 SPR axon chain
│        └──ac-snl18_lnk_1
│           ├──lamina VII of gray matter of spinal cord in L1 spinal segment layer 7 *
│           │  ├──L1 spinal segment *
│           │  │  └──first lumbar spinal cord segment *
│           │  └──lamina VII of gray matter of spinal cord * ...
│           └──ac-snl18_lnk_2
│              ├──White matter of CNS in L1 spinal segment layer 14 *
│              │  ├──L1 spinal segment * ...
│              │  │   *
│              │  └──White matter of CNS * ...
│              └──ac-snl18_lnk_3
│                 ├──L1 ventral root *
│                 │  └──ventral nerve root of lumbar spinal cord *
│                 └──ac-snl18_lnk_4
│                    ├──L1 white ramus *
│                    │  └──White communicating ramus of first lumbar anterior ramus
│                    └──ac-snl18_lnk_5
│                       └──L1 sympathetic ganglion *
│                          └──First lumbar ganglion
```

**Comment by albatros13** [comment]
Two readOnly properties were added to the apinatomy's Node resource: for chain leaves, node.nextChainRoots points to the roots of joint chains; for chain roots, node.prevChainLeaves points to the leaves of the joint chains.

**Comment by tgbugs** [comment]
Question: next and prev are defined for links and that is what I traverse for the queries, but these are defined over nodes, this makes querying difficult, is it possible to define an equivalent to nextChainRoots/prevChainLeafs that connects links?

**Comment by albatros13** [comment]
Replaced nextChainRoots/prevChainLeaves pair on Nodes with nextChainStartLevels/prevChainEndLevels on Links to enable easier queries for SciGraph path search.
