### ISSUE TITLE
Adding text labels and ontology term annotations to layers

### ISSUE THREAD

**Issue by bdebono** [open-physiology/open-physiology-viewer#216]
As we progress with the WBKG, we have reached the point where a detailed layered map of the gastrointestinal tract is being produced.

We anticipate to generate around 50 lyphs each bearing around 10 layers - for example, layering looks something like this:

https://en.wikipedia.org/wiki/Submucosa#/media/File:GI_Organization.svg 

As the biological name of a layer is not always related to the constituent material (also, sometimes for reasons of convenience, the same generic tissue material may be used in different lyph/layer contexts - e.g. a smooth muscle material may be applied to both circular and longitudinal muscle layers). It would therefore be useful to have the means to provide, in the spreadsheet, an ordered list of [i] layer names as well as an ordered list of [ii] ontology term IDs that correspond the the ordered list of [iii] materials from which layers are constituted.

**Comment by bdebono** [comment]
Also, please find below the link to the spreadsheet on which we are building the gastrointestinal tract for the wbkg:

https://docs.google.com/spreadsheets/d/1sNa8Vtlb6t_OkoAqdbDuxjw_RYuZJ8svVv8YMjOQF4s/edit#gid=389462901

**Comment by albatros13** [comment]
Since we agreed that this can be done via lyph templates, I am closing this issue (it can be reopened at any time should any code changes be required to make the process more handy for the modellers).
