### ISSUE TITLE
missing prefix in local conventions results in very strange issue with namespace expansion when there is a reference that uses the missing namespace

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#220]
e.g. if DOI is missing from localConventions then somehow the parent object namespace manages to get changed from `ilxtr` to `DOI`.

**Comment by tgbugs** [comment]
hrm, or not, it seems that there is some code path for serializing nested ids that conflates the namespace of the object with the namespace for all ids in lists inside that object, which is in correct

**Comment by tgbugs** [comment]
```jsonld
    {
      "id": "PMID:27783854",
      "fullID": "PMID:27783854",
      "namespace": "PMID",
      "class": "Reference",
      "uri": "https://pubmed.ncbi.nlm.nih.gov/27783854/",
      "documents": [
        "ard-arm-cardiac",
        "neuron-5",
        "neuron-11",
        "neuron-13"
      ]
    },
```

**Comment by tgbugs** [comment]
[aacar-namespace-issue.zip](https://github.com/open-physiology/open-physiology-viewer/files/9677996/aacar-namespace-issue.zip)

**Comment by albatros13** [comment]
Can you please provide a link to the input model

**Comment by albatros13** [comment]
1. Missing reference in local conventions is a model error
2. Since then we changed the way the namespaces of external resources are handled - namespace from the local convention is used, so I believe the issue is resolved (reopen otherwise)
