### ISSUE TITLE
OntologyTerm object only constructed for groups but not lyphs or materials

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#222]
see e.g. aacar where only the neuron type ontology ids have ontology terms constructed for them in the generated json, while all ids on lyphs or materials are missing an OntologyTerm object.

**Comment by tgbugs** [comment]
Only groups get their internal resources copied, this is not done for lyphs etc. They are generated, but no longer are lifted out to the top level ontologyTerms list (they used to be lifted out). Restoring the lifting out specifically for ontology terms, references, and externals should resolve the issue by restoring the old behavior.

**Comment by tgbugs** [comment]
May want to add the transitive version of these for the whole graph so that we can address Dave's issue with knowing whether an reference was attached to the whole graph or to one of the neuron populations. E.g. `transitiveOntologyTerms` `transitiveReferences` or similar.

**Comment by albatros13** [comment]
Fixed by including "ontologyTerms", "references" and "external" into the property map of utils.js/mergeWithModel. 
This function adds typed generated resources to the model
