### ISSUE TITLE
How to find HousingLyphs and Chains for Dynamic Groups Lyphs

### ISSUE THREAD

**Issue by jrmartin** [open-physiology/open-physiology-viewer#223]
In dynamic groups:
- How do we know what is the HousingLyph for each Lyph? 
- How do we find the Chain that contains the Lyph?
- How do we extract the hostedBy and wiredTo properties from the Lyph's Chain? We need these properties to know where to place Lyphs and Chains to the scaffold. 

Model we are testing: https://github.com/open-physiology/open-physiology-viewer/blob/master/test/data/wbkgCardiac.json

**Comment by albatros13** [comment]
//Find housing lyphs for neuron groups
        let n5 = graphData.dynamicGroups.find(g => g.id === "neuron-5");
        let hostedLinks = n5.links.filter(l => l.fasciculatesIn || l.endsIn);
        let housingLyphs = hostedLinks.map(l => l.fasciculatesIn || l.endsIn); //links -> lyphs 
        let hostedHousingLyphs = housingLyphs.map(l => l.hostedBy); //lyphs -> regions
//Find housing lyph chains 
        let houisingChains = houisingLyphsInChains.map(h => h.axis.levelIn)::flatten(); // lyphs -> links -> chains, each link can be part of several chains, hence levelIn gives an array that we need to flatten
        let wiredHousingChains = houisingChains.filter(c => c.wiredTo).map(c => c.wiredTo); // chains -> wires
        let housingChainRoots = houisingChains.filter(c => c.root).map(c => c.root); // chains -> nodes
        let housingChainLeaves = houisingChains.filter(c => c.leaf).map(c => c.leaf);
        let anchoredHousingChainRoots = housingChainRoots.filter(n => n.anchoredTo);  //nodes -> anchors
        let anchoredHousingChainLeaves = housingChainLeaves.filter(n => n.anchoredTo);
        let hostedHousingChains = houisingChains.filter(c => c.hostedBy).map(c => c.hostedBy); //chains -> regions

**Comment by albatros13** [comment]
See comment. There is also test in index.spec.js, "Find paths from neurons to scaffold wires (via housing lyphs)", that runs the code above

**Comment by jrmartin** [comment]
@albatros13 Thanks for that information Natallia. With the examples provided, we can retrieve the housing lyphs for the lyphs of the selected dynamic group. However, the hostedBy and wiredTo properties are undefined. Is the wbkCardiac.json model expected to have Dynamic Groups with Lyphs that are hostedBy or wiredTo scaffold components?

**Comment by jrmartin** [comment]
Tested again with latest wbkgCardiac and did work, closing issue
