### ISSUE TITLE
Link's fasciculateIn property not populated correctly 

### ISSUE THREAD

**Issue by ddelpiano** [open-physiology/open-physiology-viewer#232]
As showed at the end of the last sprint meeting during the debugging, the links don't have the FasciculateIn property correctly filled.

For example:
Using scaletta #4 model, the links are fasciculating on the housing lyphs instead of the layers. For Neuron 8, we would expect the Links to 'fasciculateIn' the housingLayer, but are currently on the housing lyph.

![image](https://user-images.githubusercontent.com/4562825/213226907-01d9c8ab-d067-4bf5-b24d-0db9170acbee.png)

**Comment by albatros13** [comment]
A fix commited - please verify and close if it works

**Comment by albatros13** [comment]
Based on the latest progress with Neuroview, I assume the generation problem is solved.
