### ISSUE TITLE
Reference resource type

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#27]
When converting ApiNATOMY models to JSON-LD external ontology identifiers and references are currently conflated. To avoid this it would be helpful to have a Reference type that was a subclass of the External type that would make it possible to distinguish between external ontology ids and literature references since the semantics are significantly different.

Writing this I also realize that it might make sense to create another subclass of external ids that are OntologyId or OntologyTerm which would provide a way to differentiate ontology ids from other external ids rather than making them the default interpretation (if they continue to be of type External).

As the publication key has already been split from the external key in the model, it might make sense to have an edge that is ontologyTerm with specific semantics as well which could be used to unambiguously translate to rdf:type using the json-ld `@context`. This would (for example) make it possible to automatically include axon segments as the type of the named individual links/lyphs from the model.

**Comment by albatros13** [comment]
Please replace property "publications" to "references" in all meaningful ApiNATOMY models. 
You can also rename "external" to "ontologyTerms" or move ontology terms to a new column "ontologyTerms" if you want these resources to have OntologyTerm class in the JSON-LD export.

**Comment by tgbugs** [comment]
I have fixed all the google sheets that are in the apinatomy-models repo, any other sheets that are in use should be updated as well.

**Comment by tgbugs** [comment]
@albatros13 did the resource type for references change in the expansion from Publication -> External? If so that is undesirable. I am having to update all my queries to match this and it seems that the types have changed as well?

**Comment by tgbugs** [comment]
It looks like the schema changed to Reference however it does not seem to be getting picked up correctly in the expansion?

**Comment by albatros13** [comment]
The problem was caused by an obsolete and redundant property "references" in class "Group" while a more general property of type Reference is specified in the base class Resource.
