### ISSUE TITLE
in chains with a single explicit root or leaf that node should be a root

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#31]
While working out the issues with connectivity queries today we ran into a major point of confusion that should not be allowed to happen. All the dendrite chains had been specified as being "leafed" that is, they had a leaf but no root. For sake of sanity chains with only a single explicit root/leaf should have that be the root. This helps with the follow-your-nose approach to exploring apinatomy models and provides unambiguous behavior when only a single named (not generated) node is associated with a chain. Otherwise you have to query all chains in both directions.

**Comment by albatros13** [comment]
Is this still relevant? There was also a bug (fixed now) related to the absence of a root (chain.root would be undefined or null) while in practice the first node of the level link is a root. Generally, there is a piece of code to issue a warning if a chain has no root: CHAIN_NO_ROOT: "A chain without root", but this is just a safeguard as model generator should always assign missing root property from the context. 
At the same time, I do not think it's appropriate to mask modelling issues and override modeller's instructions reassigning a specified leaf to the root, this is likely to cause confusion and break valid models.

**Comment by tgbugs** [comment]
This one is tricky. I know why I proposed it, but I agree that it is problematic because we don't want to change what is in the input model. The issue is that we really want the input interface for chains to be decoupled from the input schema so that if a single named node is provided it is always a root and never expose the root/leaf abstraction to the user, however we can't do that right now.

One potential solution is to issue a warning if a chain is specified with only a leaf and no root?

**Comment by albatros13** [comment]
Ok, I can make "root" a required field in the schema, it will be manifested
as an error if chain specification has no explicit root in the input model.
