### ISSUE TITLE
Graph resource needs an "abbreviation" field for use in generating rdfs:labels.

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#32]
This is needed so that we can add a `label (abbrev)` suffix to all generated labels during export to jsonld to make it quick to identify the source of an entity.

**Comment by albatros13** [comment]
Is this still relevant? Can you give an example?

**Comment by tgbugs** [comment]
https://github.com/open-physiology/apinatomy-models/blob/e415635ae759205d4c0bd1da2af958a3903df6b2/models/keast-bladder/source/keast-bladder.json#L5658-L5659

Would appear as

```json
    "id": "keast-bladder",
    "abbrev": "kblad",
    "name": "Keast ApiNATOMY model of bladder innervation"
```
