### ISSUE TITLE
json-ld general issue

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#38]
apinatomy:nodes and apinatomy:links do not have `"@type": "@id"` apparently?

**Comment by albatros13** [comment]
I am adding test for the whole model to JSON-LD converter. Any other requirements we need to make sure hold in the generated model?

**Comment by tgbugs** [comment]
Nothing that I'm aware of at the moment.

**Comment by albatros13** [comment]
Test added, @type: @id is present for links and nodes as well as for other connectivity model resources.
