### ISSUE TITLE
region z-fighting

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#43]
The surfaces of regions need to have a polygon priority ordering to keep regions from z-fighting. Sometimes this could be inferred from the order in which scaffolds are loaded, but other times we would always want the F component to be below the D component because F is larger than D.

**Comment by albatros13** [comment]
This was important for the version of TOO map that had segment regions. 
For the TOO map with elliptic wires this is irrelevant. PoligonOffsetFactor set in the scaffold model can help to resolve the conflicts. Implementing analysis for region overlap and z-conflict resolution based on size/area is a computational overhead that does not seem to be well justified in practice.
