### ISSUE TITLE
embed graphScheme version in json input models

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#46]
Maybe take the "$id" field from graphScheme and embed it under "schema_version"? This means that "$id" would need to include the version number in its uri.

**Comment by albatros13** [comment]
The field $id points to https://github.com/open-physiology/open-physiology-viewer/blob/master/src/model/graphScheme.json
and will always give the latest committed schema version.

To refer to a specific schema version, the closest solution I found is to retrieve the latest commit id involving the graphSchema.json at a given moment:
git log -n 1 --pretty=format:%H -- src/model/graphScheme.json
> 8b515e3b82e3eb2d655c27c557e54633503a7e92
and then access the file:
https://raw.githubusercontent.com/open-physiology/open-physiology-viewer/8b515e3b82e3eb2d655c27c557e54633503a7e92/src/model/graphScheme.json

But git log works with local history. This commit number (or the corresponding schema version file) must be explicitely recorded somewhere to be used in a deployed app...

**Comment by albatros13** [comment]
Schema version is generated by object hash
