### ISSUE TITLE
Coalescences check box appears to have opposite effect

### ISSUE THREAD

**Issue by dbrnz** [open-physiology/open-physiology-viewer#7]
The earlier version of `graph.json` (before commit 030d687) contains an example of a coalescence between lyph 78 and lyph 24. However these two lyphs are only adjacent in the viewer when the `Coalescences` box is unchecked:

> ![screen shot 2018-11-20 at 4 15 49 pm](https://user-images.githubusercontent.com/239220/48749549-56ecf780-ece0-11e8-892d-bd29dad62b32.png)

The lyphs drift apart when the box is checked:

> ![screen shot 2018-11-20 at 4 16 05 pm](https://user-images.githubusercontent.com/239220/48749572-6cfab800-ece0-11e8-92c9-d5484259d1bc.png)

**Comment by dbrnz** [comment]
NB. The `graph.json` file referred to has since been renamed and moved to the `test/data` directory -- the example coalescence now exists in `centralNeuralSystem.json`, `centralNeuralSystem.json` and `collapsible.json`.

**Comment by albatros13** [comment]
The issue is not relevant anymore
