### ISSUE TITLE
Document and revise group inclusion algorithm

### ISSUE THREAD

**Issue by albatros13** [open-physiology/open-physiology-viewer#73]
Groups are stand-alone subgraphs that can be toggled on the screen.
Groups can either be defined by user or created automatically from templates
Sometimes it makes sense to add extra resources to existing groups.
For example, a referece to a non-existing lyph from a  group triggers the following chain: 
1. lyph resource is generated, 
2. a link it conveys is generated, 
3. source and target nodes for the link are generated
This link and and both end nodes must be included to all the groups in which the original lyph appears.
Such  dependency inclusion rules can be even more complex
We need to document all operations the tool performs to define group scope.

**Comment by tgbugs** [comment]
This will be related to the neurulator.

**Comment by albatros13** [comment]
See documentation at http://open-physiology-viewer-docs.surge.sh/manual/model.html#group
