### ISSUE TITLE
Error when loading sawg-distal-colon-model.xlsx.

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#79]
https://github.com/open-physiology/apinatomy-models/blob/master/sawg-distal-colon/source/sawg-distal-colon.xlsx
![apinat-sdc-bug](https://user-images.githubusercontent.com/4299776/112905790-de608780-909f-11eb-93ce-1bbe23be2101.png)

**Comment by albatros13** [comment]
Obsolete model, no issues with the modern version:
https://github.com/open-physiology/apinatomy-models/blob/master/models/sawg-distal-colon/source/sawg-distal-colon.xlsx
