### ISSUE TITLE
fail loudly if localConventions are missing and a curied identifier is used

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#80]
Had a failure loading the distal colon model today because the localConventions sheet was missing, if an error was produced when a curie is used in an identifier field and it is unknown, that will prevent silent data corruption and confusion on the part of the user.

**Comment by tgbugs** [comment]
Was bitten by this again. @MCSZ until this is fixed can you please double check that all the curie prefixes used in the files are in the localConvetions sheet? I think I have sorted out all of them (NCIT was undefined for a number of sheets).

**Comment by albatros13** [comment]
An error-level message added to generation logs if external resources with curie not in local conventions are found.
