### ISSUE TITLE
dynamic group identifiers for mapping to external ids

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#81]
When a dynamic group is generated we need a way to give it an identifier before it is generated so that we can attach metadata about it. Essentially given an identifier for the dynamic group and one or more expected members of that group e.g. a node, lyph, or link, when a dynamic group is generated it check to see if it contains those members, and if it does, then it uses the identifier provided in the template and fills in any data associated with that identifier.

A warning/error should be issued if multiple distinct dynamic groups match the same set of defining identifiers because it indicates that there is some unexpected overlap. This will need a bit of consideration because there are many possible dynamic groups that might not be identical and yet have overlapping members. One way around this would be to note which process generated the dynamic group e.g. neurulator dynamic groups, scigraph query dynamic groups, etc.

**Comment by albatros13** [comment]
This issue seems to be solved long ago via "seed" and "seedIn" properties
