### ISSUE TITLE
can't load scaffolds

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#86]
I'm trying to load the `tooMap.json` scaffold and am getting `An unexpected error occurred: TypeError: this._graphData.neurulator is not a function` because I think some code is trying the neurulate a scaffold.

**Comment by albatros13** [comment]
Hi Tom,

yes, there is no check before calling neurulator whether we work with
connectivity model or scaffold, I discovered it independently when working
on putting TooMAp to Excel, it will be fixed by Monday.

Regards,
Natallia

**Comment by albatros13** [comment]
Done
