### ISSUE TITLE
schema for saving one or more states of the viewer

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#88]
We need a format that records
1. scaffolds loaded
2. connectivity models loaded
3. scenes and scene ordering
For each scene we need to save
1. visibility of scaffold and connectivity components
2. position of scaffold and connectivity components

**Comment by albatros13** [comment]
The schema and basic UI are added. Some revision is needed in the UI to be able to preserve and return to the unsaved state that was  in the viewer before one loaded a state from a snapshot.

**Comment by albatros13** [comment]
Added tests for checking operations on scaffolds.
