### ISSUE TITLE
chain template expansion incorrectly creates links when they already exist

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#91]
We have been experimenting with using chains to simplify the specification of the vagus nerve model, and in the process realized that we can specify a chain where some of the lyphs already have links and nodes associated. Unfortunately when we do this the chain template expansion ignores existing links conveyed by a lyph and generates new ones. A file that causes the issue is attached.
[Vagus_Flatmap(8).xlsx](https://github.com/open-physiology/open-physiology-viewer/files/6780732/Vagus_Flatmap.8.xlsx)

**Comment by albatros13** [comment]
Added check to find links before creating new ones. This change breaks one of the automated tests, so the issue will be closed after inspection of the test.

**Comment by albatros13** [comment]
All tests are working
