### ISSUE TITLE
trailing comma results in empty id in internalLyphs which breaks the new hidden propagation code

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#96]
This line is where the error occurs. https://github.com/open-physiology/open-physiology-viewer/blob/242acf3e596ed996e60824350a73e2730739f3b8/src/model/shapeModel.js#L397
The offending [model.xlsx](https://github.com/open-physiology/open-physiology-viewer/files/6889151/model.xlsx) has the problem in lyphs `S41`.

The underlying issues is that there is a cell with internal lyphs specified as `a,b,c, ` it might also happen with `a,b,c,`. The trailing comma with nothing following it should be removed from the list not treated as the empty string.

**Comment by albatros13** [comment]
Done
