### ISSUE TITLE
add next/prev relationship between links that share a node between chains

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#97]
For example the node `ns23` in keast bladder is common between `ac-snl16_lnk_7`, `ac-snl26_lnk_7`, and `ac-l1l26a_lnk_1`, however `ac-l1l26a_lnk_1` is not listed as `next` for `ac-snl16_lnk_7` and `ac-snl26_lnk_7`. This is needed to simplify the ordering rules for neurulated links so that we do not have to traverse `target` `rootOf` and `layers` (pulling in unwanted nodes). For the record here is a version of the keast model that demonstrates the issue https://raw.githubusercontent.com/open-physiology/apinatomy-models/cb4cbb1ee62e0f75d36504820c8b56f6082971b7/keast-bladder/source/keast-bladder.json.

**Comment by albatros13** [comment]
This problem has been addressed in the closed issue #129: we agreed not to mix prev/next properties within the same chain with nextChainStartLevels/prevChainEndLevels properties that interconnect start and end levels of neighboring chains. For the model in the issue, the links in question currently are linked:
    {
      "id": "ac-l1l26a_lnk_1",
      ...
      "prevChainEndLevels": [
        "ac-snl16_lnk_7",
        "ac-snl26_lnk_7"
      ]
