### ISSUE TITLE
fasciculatesIn is incorrect for links with bag topology

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#98]
Given that fasciculatesIn implies that the source and target of a link sit on the border of the housing lyph and given that bag topology implies that a lyph ends somewhere inside a housing lyph and does not span it, we need a way to distinguish between the two cases. I recall discussing this before but I can't find an issue. The cases below work out as follows I think.
**A.** Ok and should be default for chain generation. However, the underlying link does not have a fasciculatesIn relation to the housing lyph which needs to be fixed.
**B.** Probably ok but not the default when generating from chains. It seems unusual that a bag would always end exactly on a regional boundary, in fact statistically it should almost never happen unless the bag itself defines the regional boundary. Not clear if this is fasciculatesIn, for just the link it is strictly correct, but confusing because the surrounding lyph itself does not fasciculate due to the bag topology.
**C.** This topology can happen, but unless it is something like a channel or a pathological state such as a haemorrhage then it seems unlikely. The haemorrhage case also seems like the housing lyph itself would be cut, so are there other examples of open tubes just ... hanging out in housing lyphs? Microtubules ends maybe? This also does not have the fasciculatesIn relationship to the housing lyph.
**D.** This is the only one that is unambiguous fasciculatesIn.
![apinat-fasciculates](https://user-images.githubusercontent.com/4299776/127387331-53c80da4-551d-4784-be60-7fe3c2645895.png)

This is slightly related to https://github.com/open-physiology/open-physiology-viewer/issues/41

**Comment by albatros13** [comment]
A pair of properties "endsIn" and "endBundles" is now used for the case A (and C).
